Repository featurehub-io/featurehub, pull requests merged in 2022-10, with the labels that each got.

#854 [bufgix/internal-urls] Mount metrics and health on /
  backend/common-web/src/main/kotlin/io/featurehub/health/MetricsHealthRegistration.kt
  backend/common-web/src/main/kotlin/io/featurehub/jersey/AdminAppStaticHttpHandler.kt
  backend/common-web/src/main/kotlin/io/featurehub/jersey/DelegatingHandler.kt
  backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt
  backend/mr-db-api/src/main/java/io/featurehub/db/api/OrganizationApi.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/OrganizationSqlApi.java
  backend/mr/src/main/java/io/featurehub/mr/resources/SetupResource.java
  backend/mr/src/main/resources/deploy-defaults/common.properties
  backend/party-server/src/test/resources/application.properties
Labels: bug

#851 [bugfix/fastly-sse-cache] Fixed Fastly SSE Cache Header
  backend/edge-common/src/main/kotlin/io/featurehub/edge/EdgeCommonFeature.kt
  backend/edge-common/src/main/kotlin/io/featurehub/edge/utils/FastlySSEContainerResponseFilter.kt
  backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CloudEventCacheBroadcaster.kt
  backend/party-server/src/test/resources/log4j2-test.xml
  backend/release.sh
  backend/tile-app-with-ui/tile.xml
  current-rc.txt
  docs/modules/ROOT/pages/migration.adoc
Labels: bug

#857 [internal/1.5.9 release branch] minor bugfixing for 1.5.9 release
  adks/e2e-sdk/features/strings.feature
  admin-frontend/open_admin_app/lib/widgets/features/feature_names_left_panel.dart
  backend/common-web/src/main/kotlin/io/featurehub/health/MetricsHealthRegistration.kt
  backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/pubsub/PubsubDachaEventsListener.kt
  backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureUpdate.kt
  backend/edge-full/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java
  backend/edge-full/src/main/kotlin/io/featurehub/edge/StreamingFeatureSource.kt
  backend/edge-full/src/main/kotlin/io/featurehub/edge/events/kinesis/KinesisEdgeFeature.kt
  backend/edge-full/src/main/kotlin/io/featurehub/edge/events/nats/NatsEdgeFeature.kt
  backend/edge-full/src/main/kotlin/io/featurehub/edge/events/nats/NatsFeatureListener.kt
  backend/edge-full/src/main/kotlin/io/featurehub/edge/events/nats/NatsFeatureUpdatePublisher.kt
  backend/edge-full/src/main/kotlin/io/featurehub/edge/events/nats/NatsOriginalListener.kt
  backend/edge-full/src/main/kotlin/io/featurehub/edge/events/pubsub/PubsubEdgeFeature.kt
  backend/edge-full/src/test/resources/application.properties
  backend/edge-stats-emitter/src/main/kotlin/io/featurehub/edge/stats/PubsubStatsPublisher.kt
  backend/edge-stats-emitter/src/main/kotlin/io/featurehub/edge/stats/StatPublisher.kt
  backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventReceiverRegistry.kt
  backend/eventing-kinesis/src/main/kotlin/io/featurehub/events/kinesis/KinesisFactory.kt
  backend/eventing-nats/src/main/kotlin/io/featurehub/publish/NATSFeature.kt
  backend/mr-db-ebean/src/main/resources/dbmigration/oracle/1.16.sql
  backend/mr-db-services/src/main/kotlin/io/featurehub/db/services/ConvertUtils.kt
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AdminServiceAccount2Spec.groovy
  backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CacheMetrics.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/dacha2/pubsub/PubsubMRFeature.kt
  backend/party-server/src/main/kotlin/io.featurehub.party/Application.kt
  backend/party-server/src/test/resources/application.properties
  backend/party-server/src/test/resources/log4j2-test.xml
  docs/modules/ROOT/pages/metrics.adoc
Labels: bug

#858 Various responsiveness fixes
  admin-frontend/open_admin_app/lib/routes/loading_route.dart
  admin-frontend/open_admin_app/lib/utils/utils.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_footer_button_bar.dart
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/strategies/split_rollout_button.dart
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/value_cell_holder.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_widget.dart
  admin-frontend/open_admin_app/web/assets/loading.gif
  admin-frontend/open_admin_app/web/index.html
Labels: bug

#861 Fix search file in docs
  docs/modules/ROOT/pages/configuration.adoc
  docs/supplemental_ui/js/search-index.js
Labels: bug, docs

#863 update antora docs versions
  docs/antora-playbook.yml
Labels: docs

#864 Antora docs - add 1.5.10-rc
  docs/antora.yml
Labels: docs
