Repository featurehub-io/featurehub, pull requests merged in 2022-08, with the labels that each got.

#814 [internal/fix-openapi-upgrade] - Fixing longstanding internal inconsistency
  admin-frontend/app_mr_layer/pom.xml
  admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/strategies/add_attribute_strategy_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/strategies/multiselect_dropdown.dart
  admin-frontend/open_admin_app/lib/widgets/user/common/select_portfolio_group_bloc.dart
Labels: bug

#815 internal-ui-fixes
  admin-frontend/open_admin_app/lib/routes/manage_app_route.dart
  admin-frontend/open_admin_app/lib/theme/theme_data.dart
Labels: bug

#819 UI visual fixes
  admin-frontend/open_admin_app/lib/routes/admin_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_portfolios_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_users_route.dart
  admin-frontend/open_admin_app/lib/widgets/admin_sdk_service_account/list_admin_service_accounts_widget.dart
  admin-frontend/open_admin_app/lib/widgets/portfolio/portfolio_widget.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/stepper_container.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart
Labels: bug

#818 [feature/fastly-cache] Support a Fastly Cache on GET requests
  backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt
  backend/common-web/src/main/kotlin/io/featurehub/rest/CacheControlFilter.kt
  backend/dacha/src/main/java/io/featurehub/dacha/InternalCache.java
  backend/dacha/src/main/java/io/featurehub/dacha/ServerConfig.java
  backend/dacha/src/main/kotlin/io/featurehub/dacha/CacheUpdateListener.kt
  backend/dacha/src/main/kotlin/io/featurehub/dacha/DachaFeature.kt
  backend/dacha/src/main/kotlin/io/featurehub/dacha/caching/FastlyPublisher.kt
  backend/edge-api/sse-api.yaml
  backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureGet.kt
  docs/modules/ROOT/pages/capabilities-table.adoc
Labels: enhancement

#820 FeatureHub documentation improvements
  admin-frontend/open_admin_app/lib/widgets/stepper/stepper_container.dart
  docs/modules/ROOT/images/fh-admin-sa.png
  docs/modules/ROOT/images/fh-group-permissions.png
  docs/modules/ROOT/images/fh-sa-permissions.png
  docs/modules/ROOT/images/fh_add_user.png
  docs/modules/ROOT/images/fh_add_user_link.png
  docs/modules/ROOT/images/fh_api_keys.png
  docs/modules/ROOT/images/fh_apps_page.png
  docs/modules/ROOT/images/fh_create_feature.png
  docs/modules/ROOT/images/fh_env_order.png
  docs/modules/ROOT/images/fh_features_dahsboard.png
  docs/modules/ROOT/images/fh_lock_feature.png
  docs/modules/ROOT/images/fh_portfolios.png
  docs/modules/ROOT/images/fh_progress_helper.png
  docs/modules/ROOT/images/fh_reset_password.png
  docs/modules/ROOT/images/fh_retire_feature.png
  docs/modules/ROOT/images/fh_service_accounts.png
  docs/modules/ROOT/images/fh_split_targeting.png
  docs/modules/ROOT/images/fh_split_targeting_2.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/admin-development-kit.adoc
  docs/modules/ROOT/pages/admin-service-accounts.adoc
  docs/modules/ROOT/pages/app_setup_helper.adoc
  docs/modules/ROOT/pages/applications.adoc
  docs/modules/ROOT/pages/architecture.adoc
  docs/modules/ROOT/pages/environments.adoc
  docs/modules/ROOT/pages/evaluation.adoc
  docs/modules/ROOT/pages/features.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/installation.adoc
  docs/modules/ROOT/pages/metrics.adoc
  docs/modules/ROOT/pages/portfolios.adoc
  docs/modules/ROOT/pages/service-accounts.adoc
  docs/modules/ROOT/pages/strategies.adoc
  docs/modules/ROOT/pages/users.adoc
Labels: docs

#823 Remove unused nav from docs
  docs/modules/ROOT/nav.adoc
Labels: docs
