Repository featurehub-io/featurehub, pull requests merged in 2022-07, with the labels that each got.

#796 Add docs - admin service accounts
  admin-frontend/open_admin_app/lib/widgets/setup/page1_widget.dart
  docs/modules/ROOT/pages/admin-development-kit.adoc
  docs/modules/ROOT/pages/identity.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: docs

#807 [feature/metrics] - Updated metrics
  admin-frontend/app_mr_layer/pom.xml
  admin-frontend/app_mr_layer/pubspec.yaml
  backend/common-web/src/main/kotlin/io/featurehub/health/LoadBalancerResource.kt
  backend/common-web/src/main/kotlin/io/featurehub/jersey/DelegatingHandler.kt
  backend/common-web/src/main/kotlin/io/featurehub/logging/MetricLogEnhancer.kt
  backend/common-web/src/main/kotlin/io/featurehub/metrics/MetricsCollector.kt
  backend/common-web/src/main/resources/META-INF/services/cd.connect.logging.JsonLogEnhancer
  backend/composite-common/pom.xml
  backend/composite-jersey/pom.xml
  backend/composite-prometheus/pom.xml
  backend/dacha-api/pom.xml
  backend/dacha/src/main/java/io/featurehub/dacha/CacheManager.java
  backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java
  backend/dacha/src/main/java/io/featurehub/dacha/ServerConfig.java
  backend/edge-api/pom.xml
  backend/edge-feature-update-async-api/pom.xml
  backend/edge-full/src/main/java/io/featurehub/edge/rest/EventStreamResource.java
  backend/edge-rest/src/main/kotlin/io/featurehub/edge/resources/EdgeResource.kt
  backend/edge-stats-api/pom.xml
  backend/mr-api-java-server/pom.xml
  backend/mr-db-sql/src/main/java/io/featurehub/db/publish/NamedCacheListener.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/ConvertUtils.java
  backend/mr/src/test/resources/log4j2-test.xml
  backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/OauthResource.kt
  backend/security-saml/src/main/kotlin/io/featurehub/web/security/saml/SamlResource.kt
  backend/tile-java/tile.xml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/admin-development-kit.adoc
  docs/modules/ROOT/pages/metrics.adoc
  infra/api-bucket/files/edge/1.1.3.yaml
  infra/api-bucket/files/edge/releases.json
  infra/api-bucket/files/mrapi/1.1.8.yaml
  infra/api-bucket/files/mrapi/releases.json
  infra/api-bucket/files/releases.json
Labels: enhancement

#810 Fix error messages and add a util method for url validation
  admin-frontend/open_admin_app/lib/routes/edit_admin_service_account_route.dart
  admin-frontend/open_admin_app/lib/utils/utils.dart
  admin-frontend/open_admin_app/lib/widgets/apps/manage_service_accounts_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/group/group_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_bloc.dart
Labels: bug

#811 fix loading indicators
  admin-frontend/open_admin_app/lib/routes/apps_route.dart
  admin-frontend/open_admin_app/lib/routes/create_admin_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/routes/create_user_route.dart
  admin-frontend/open_admin_app/lib/routes/edit_user_route.dart
  admin-frontend/open_admin_app/lib/routes/service_env_route.dart
  admin-frontend/open_admin_app/lib/utils/utils.dart
  admin-frontend/open_admin_app/lib/widgets/admin_sdk_service_account/list_admin_service_accounts_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/manage_service_accounts_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_loading_error.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_loading_indicator.dart
  admin-frontend/open_admin_app/lib/widgets/portfolio/portfolio_widget.dart
  admin-frontend/open_admin_app/lib/widgets/user/common/portfolio_group_selector_widget.dart
  admin-frontend/open_admin_app/lib/widgets/user/create/create_user_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart
Labels: bug
