Repository featurehub-io/featurehub, pull requests merged in 2022-03, with the labels that each got.

#724 Feature/meta data description
  backend/mr-api-java-server/pom.xml
  backend/mr-api/mr-api.yaml
  backend/mr-api/pom.xml
  backend/mr-db-api/src/main/java/io/featurehub/db/api/ApplicationApi.java
  backend/mr-db-api/src/main/java/io/featurehub/db/api/FeatureApi.java
  backend/mr-db-api/src/main/java/io/featurehub/db/api/FillOpts.java
  backend/mr-db-ebean/src/main/resources/dbmigration/h2/1.13.sql
  backend/mr-db-ebean/src/main/resources/dbmigration/model/1.13.model.xml
  backend/mr-db-ebean/src/main/resources/dbmigration/mysql/1.13.sql
  backend/mr-db-ebean/src/main/resources/dbmigration/oracle/1.13.sql
  backend/mr-db-ebean/src/main/resources/dbmigration/postgres/1.13.sql
  backend/mr-db-models/src/main/java/io/featurehub/db/model/DbApplicationFeature.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/ApplicationSqlApi.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/Conversions.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/ConvertUtils.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/FeatureSqlApi.java
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Base2Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureStandaloneSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/StrategyDifferUtilsSpec.groovy
  backend/mr/src/main/java/io/featurehub/mr/resources/FeatureResource.java
  current-rc.txt
  e2e/test/features/meta_data.feature
  e2e/test/steps/ApplicationStepdefs.dart
  e2e/test/steps/FeatureStepdefs.dart
Labels: enhancement

#736 [feature] Support multi-architecture builds
  backend/build.sh
  backend/dacha/src/main/java/io/featurehub/dacha/ServerConfig.java
  backend/party-server/pom.xml
  backend/release.sh
  backend/tile-app-with-ui/tile.xml
  backend/tile-app/tile.xml
  pipeline/build/base_party/Dockerfile
  pipeline/build/base_party/make-image.sh
Labels: enhancement

#738 [feature] Support Heartbeats in SSE
  backend/edge-full/src/main/java/io/featurehub/edge/bucket/BucketService.java
  backend/edge-full/src/main/java/io/featurehub/edge/bucket/EventOutputBucketService.java
  backend/edge-full/src/main/java/io/featurehub/edge/bucket/TimedBucket.java
  backend/edge-full/src/main/java/io/featurehub/edge/bucket/TimedBucketSlot.java
  backend/edge-full/src/main/java/io/featurehub/edge/bucket/TimerBucketPurpose.java
  backend/edge-full/src/main/java/io/featurehub/edge/client/ClientConnection.java
  backend/edge-full/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java
  backend/party-server/src/test/resources/log4j2-test.xml
Labels: enhancement

#740 [internal] fixing the initial setup and use of the Rocket quick-start
  admin-frontend/open_admin_app/lib/api/client_api.dart
  admin-frontend/open_admin_app/lib/common/stream_valley.dart
  admin-frontend/open_admin_app/lib/config/route_handlers.dart
  admin-frontend/open_admin_app/lib/routes/apps_route.dart
  admin-frontend/open_admin_app/lib/routes/features_overview_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_app_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_group_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/external_docs_links_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_appbar.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_scaffold.dart
  admin-frontend/open_admin_app/lib/widgets/environments/env_list_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/create_update_feature_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/setup/page3_widget.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_widget.dart
Labels: bug

#741 fix docs links
  docs/images/Ruby_NewLogo_Vertical.png
  docs/images/fh-features-console-dark.png
  docs/images/languages.png
  docs/modules/ROOT/pages/architecture.adoc
  docs/modules/ROOT/pages/capabilities-explained.adoc
  docs/modules/ROOT/pages/capabilities-table.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/sdks-development.adoc
  docs/modules/ROOT/pages/sdks.adoc
  readme.adoc
Labels: bug, docs

#742 fix doc sdk link
  docs/modules/ROOT/pages/index.adoc
Labels: bug

#743 Release 1.5.7 docs
  docs/antora-playbook.yml
  docs/antora.yml
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/installation.adoc
Labels: docs

#744 readme broken link fix
  readme.adoc
Labels: bug

#746 UI fixes
  admin-frontend/open_admin_app/lib/api/client_api.dart
  admin-frontend/open_admin_app/lib/widgets/features/create_update_feature_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/features_overview_table_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/setup/page3_widget.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_widget.dart
  admin-frontend/open_admin_app/lib/widgets/user/signin/signin_provider_button.dart
Labels: bug

#752 Fix environments ordering functionality on Admin UI
  admin-frontend/open_admin_app/lib/widgets/common/fh_reorderable_list_view.dart
  admin-frontend/open_admin_app/lib/widgets/environments/env_list_widget.dart
Labels: bug

#751 [feature] Support Cache Control for website and APIs
  admin-frontend/build/build.sh
  admin-frontend/pipeline-build.sh
  admin-frontend/src/main/resources/post-build-assembly.xml
  admin-frontend/src/main/resources/pre-build-assembly.xml
  backend/common-web/src/main/kotlin/io/featurehub/jersey/AdminAppStaticHttpHandler.kt
  backend/common-web/src/main/kotlin/io/featurehub/rest/CacheControlFilter.kt
  backend/edge-full/src/main/java/io/featurehub/edge/Application.java
  backend/edge-rest/src/main/kotlin/io/featurehub/edge/Application.kt
  backend/mr/src/main/java/io/featurehub/mr/ManagementRepositoryFeature.java
  backend/party-server-ish/src/main/kotlin/io.featurehub.party/Application.kt
  backend/party-server/src/main/kotlin/io.featurehub.party/Application.kt
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/configuration.adoc
  docs/modules/ROOT/pages/installation.adoc
Labels: enhancement

#756 [internal] Internal refinement of feature update listener
  backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureUpdate.kt
  backend/mr-db-sql/src/main/java/io/featurehub/db/listener/FeatureUpdateListener.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/publish/MRPublishModule.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/publish/NATSPublisher.java
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/publish/FeatureUpdateListenerSource.kt
Labels: enhancement
