Repository featurehub-io/featurehub, pull requests merged in 2022-09, with the labels that each got.

#824 Update Groups table + ability to rename service accounts + other UI improvements
  admin-frontend/open_admin_app/lib/routes/manage_group_route.dart
  admin-frontend/open_admin_app/lib/theme/theme_data.dart
  admin-frontend/open_admin_app/lib/widgets/apps/app_update_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_alert_dialog.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_appbar.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_drawer.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ServiceAccountSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ServiceAccount2Spec.groovy
Labels: improvement

#828 [internal/docs] SDK docs update
  docs/modules/ROOT/pages/sdks-development.adoc
Labels: docs

#829 [bugfix/SAML] Single login bugfix
  backend/mr/pom.xml
  backend/mr/src/main/java/io/featurehub/Application.java
  backend/party-server-ish/pom.xml
  backend/party-server-ish/src/main/kotlin/io.featurehub.party/Application.kt
  backend/release.sh
  backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/OAuth2Feature.kt
  backend/security-saml/src/main/kotlin/io/featurehub/web/security/saml/EnvironmentalSamlServiceProviderConfig.kt
Labels: bug

#831 Docs and UI improvements
  admin-frontend/open_admin_app/lib/config/routes.dart
  admin-frontend/open_admin_app/lib/routes/apps_route.dart
  admin-frontend/open_admin_app/lib/widgets/admin_sdk_service_account/list_admin_service_accounts_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_appbar.dart
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/strategies/add_attribute_strategy_widget.dart
  admin-frontend/open_admin_app/lib/widgets/portfolio/portfolio_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_widget.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/stepper_container.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart
  docs/modules/ROOT/pages/capabilities-table.adoc
  docs/modules/ROOT/pages/sdks.adoc
  docs/modules/ROOT/pages/users.adoc
Labels: improvement, docs

#832 fix installation docs
  docs/modules/ROOT/pages/installation.adoc
Labels: bug, docs

#834 Add ability to add metadata on a feature to the UI
  admin-frontend/open_admin_app/lib/widgets/features/feature_names_left_panel.dart
  admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/set_feature_metadata.dart
  backend/party-server/src/main/kotlin/io.featurehub.party/Application.kt
Labels: enhancement

#838 add ability to add metadata as simple string
  admin-frontend/open_admin_app/lib/common/person_state.dart
  admin-frontend/open_admin_app/lib/utils/utils.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_json_editor.dart
  admin-frontend/open_admin_app/lib/widgets/features/set_feature_metadata.dart
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart
Labels: enhancement

#843 Add metadata docs
  admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart
  docs/modules/ROOT/images/fh-metadata-edit.png
  docs/modules/ROOT/pages/features.adoc
Labels: enhancement, docs

#844 add external feature link and make it clickable in the UI
  admin-frontend/open_admin_app/lib/widgets/common/external_docs_links_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_external_link_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature_names_left_panel.dart
Labels: enhancement

#846 UI - make selectable text
  admin-frontend/build-frontend.sh
  admin-frontend/open_admin_app/lib/routes/features_overview_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_app_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_group_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/routes/service_env_route.dart
  admin-frontend/open_admin_app/lib/theme/theme_data.dart
  admin-frontend/open_admin_app/lib/widgets/admin_sdk_service_account/list_admin_service_accounts_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_header.dart
  admin-frontend/open_admin_app/lib/widgets/environments/env_list_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature_names_left_panel.dart
  admin-frontend/open_admin_app/lib/widgets/features/features_overview_table_widget.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart
  pipeline/app-build-pipeline/cloudbuild.yaml
  pipeline/build/flutter_web/make-image.sh
Labels: bug

#850 fix service account widget error
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart
Labels: bug
