Repository featurehub-io/featurehub, pull requests merged in 2023-06, with the labels that each got.

#1006 [Slack/Teams integration] Add publishers to publish feature messaging updates
  backend/eventing-kinesis/testing-setup.sh
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingStrategiesUnitSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureUpdatesPublishingSpec.groovy
  backend/mr-eventing/pom.xml
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/FeatureMessagingMetrics.kt
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/MessagingConfig.kt
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/MessagingFeature.kt
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/converter/FeatureMessagingConverterImpl.kt
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/publisher/kinesis/KinesisFeatureMessagingPublisher.kt
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/publisher/nats/NatsFeatureMessagingPublisher.kt
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/publisher/pubsub/PubsubFeatureMessagingPublisher.kt
  backend/mr/src/main/kotlin/io/featurehub/mr/ManagementRepositoryFeature.kt
Labels: enhancement

#992 [feature/troubleshooting-docs] Troubleshooting docs
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/troubleshooting.adoc
Labels: enhancement, docs

#1013 Feature: Add common symmetric encryption capability
  backend/encryption-common/pom.xml
  backend/encryption-common/src/main/kotlin/io.featurehub.encryption/SymmetricEncrypter.kt
  backend/encryption-common/src/test/groovy/io/featurehub/encryption/SymmetricEncrypterIntegrationSpec.groovy
  pom.xml
Labels: enhancement

#1021 [Internal/update guava] Internal dependency and test updates
  adks/e2e-sdk/app/steps/webhook_steps.ts
  adks/e2e-sdk/features/webhooks.feature
  adks/e2e-sdk/package-lock.json
  backend/dacha2/pom.xml
  backend/edge-full/pom.xml
Labels: dependencies

#1022 [internal/prometheus-exports] Fix default prometheus exports
  adks/e2e-sdk/features/webhooks.feature
  backend/composite-jersey/pom.xml
  backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/PersonSqlApi.kt
  current-rc.txt
  infra/api-bucket/files/webhooks/1.1.2.yaml
Labels: bug

#1023 [internal/feature-history] Allow portfolio group admin full access to feature history
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy
  backend/webhook-feature-update/sinatra-example/webhook_app.rb
Labels: enhancement
