Repository featurehub-io/featurehub, pull requests merged in 2023-10, with the labels that each got.

#1071 Docs update
  docs/modules/ROOT/pages/index.adoc
Labels: docs

#1070 Feature groups part3
  admin-frontend/open_admin_app/analysis_options.yaml
  admin-frontend/open_admin_app/lib/config/route_handlers.dart
  admin-frontend/open_admin_app/lib/routes/create_admin_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/routes/create_user_route.dart
  admin-frontend/open_admin_app/lib/routes/edit_admin_service_account_route.dart
  admin-frontend/open_admin_app/lib/routes/edit_user_route.dart
  admin-frontend/open_admin_app/lib/routes/feature_groups_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_app_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_group_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/routes/not_found_route.dart
  admin-frontend/open_admin_app/lib/routes/setup_route.dart
  admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/environment_drop_down.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_card_widget.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_delete_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_settings_side_sheet.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_update_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_groups_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/features_drop_down.dart
  admin-frontend/open_admin_app/lib/widgets/features/cell-view/strategy_tooltip.dart
  admin-frontend/open_admin_app/lib/widgets/features/cell-view/value_cell.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/custom_strategy_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/delete_strategy_icon_button.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/split_edit.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/split_rollout_button.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_boolean_value_dropdown_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/feature_cell_holder.dart
  admin-frontend/open_admin_app/lib/widgets/features/editing_feature_value_block.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/custom_column_sizer.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/features_data_source.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/features_data_table.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature_dashboard_constants.dart
  admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart
  admin-frontend/open_admin_app/pubspec.yaml
  backend/mr-api/mr-api.yaml
  backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/FeatureApi.kt
  backend/mr-db-models/src/main/java/io/featurehub/db/model/DbFeatureGroupFeature.java
  backend/mr-db-services/src/main/kotlin/io/featurehub/db/publish/CacheSourceFeatureGroupApi.kt
  backend/mr-db-services/src/main/kotlin/io/featurehub/db/publish/CacheSourceFeatureGroupSqlApi.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Base3Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingBaseUnitSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureGroupSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureUpdatesPublishingSpec.groovy
  backend/mr/src/main/kotlin/io/featurehub/mr/resources/FeatureResource.kt
  infra/api-bucket/files/mrapi/1.2.0.yaml
Labels: enhancement

#1076 [bugfix/account-perm] Fix multi-group permission issue
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
Labels: bug

#1079 [internal/security-sampl] dependency update for SAML
  backend/security-saml/pom.xml
Labels: dependencies

#1078 Feature groups fixes for value
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_boolean_value_dropdown_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_json_value_container.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_number_value_container.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_string_value_container.dart
Labels: bug, enhancement

#1081 Add FG docs
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_card_widget.dart
  docs/antora.yml
  docs/modules/ROOT/images/fg-add-feature.png
  docs/modules/ROOT/images/fg-add-rollout-strat.png
  docs/modules/ROOT/images/fg-create.png
  docs/modules/ROOT/images/fg-dashboard-view.png
  docs/modules/ROOT/images/fg-main-screen.png
  docs/modules/ROOT/images/fg-view-from-dashboard.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/feature-groups.adoc
Labels: docs
