Repository featurehub-io/featurehub, pull requests merged in 2023-02, with the labels that each got.

#926 Minor docs updates
  admin-frontend/open_admin_app/lib/api/client_api.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/edit_value_strategy_link_button.dart
  docs/modules/ROOT/pages/sdks.adoc
Labels: docs

#927 Admin UI minor fix for the copy link
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/feature_cell_holder.dart
Labels: bug

#928 [feature/allow-for-empty-dashboard] Allow for no environment dashboard
  admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart
  backend/mr-api/mr-api.yaml
  backend/mr-api/user.yaml
  backend/mr-db-sql/src/main/java/io/featurehub/db/services/UserStateSqlApi.java
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/WebhookSpec.groovy
  infra/api-bucket/files/mrapi/1.1.11.yaml
  infra/api-bucket/files/mrapi/releases.json
Labels: enhancement
