Repository featurehub-io/featurehub, pull requests merged in 2023-05, with the labels that each got.

#993 add swift docs
  docs/modules/ROOT/pages/capabilities-table.adoc
  docs/modules/ROOT/pages/sdks.adoc
Labels: docs

#994 [internal/auditing-fix] Auditing fixes
  admin-frontend/build-frontend.sh
  admin-frontend/build/build.sh
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
Labels: bug

#996 Latest SDK docs improvements
  docs/modules/ROOT/images/fh_reorder_strategies.png
  docs/modules/ROOT/pages/architecture.adoc
  docs/modules/ROOT/pages/capabilities-explained.adoc
  docs/modules/ROOT/pages/capabilities-table.adoc
  docs/modules/ROOT/pages/sdks.adoc
  docs/modules/ROOT/pages/strategies.adoc
  docs/modules/ROOT/pages/users.adoc
Labels: improvement, docs

#999 [bugfix/dacha2-reset-api-key] Cache not expiring changing api keys
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheImpl.kt
  backend/dacha2/src/test/groovy/io/featurehub/dacha2/Dacha2CacheImplSpec.groovy
  backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/MessagingFeature.kt
Labels: bug

#1001 [bugfix/version-api-fix] Not reporting version correctly
  backend/common-web/src/main/kotlin/io/featurehub/info/ApplicationVersionDiscovery.kt
  backend/edge-stats-emitter/pom.xml
Labels: bug

#1008 [internal/flutter-local-build-fix] Should be 1.11
  admin-frontend/build-frontend.sh
Labels: bug
