Repository featurehub-io/featurehub, pull requests merged in 2023-04, with the labels that each got.

#953 [bugfix/update-person] Person's details not updated after edit
  admin-frontend/open_admin_app/lib/routes/edit_user_route.dart
  admin-frontend/open_admin_app/lib/widgets/user/edit/edit_user_bloc.dart
Labels: bug

#959 [bugfix/dashboard-refresh] Fix refresh of dashboard
  admin-frontend/open_admin_app/lib/api/client_api.dart
  admin-frontend/open_admin_app/lib/common/fh_shared_prefs.dart
  admin-frontend/open_admin_app/lib/common/person_state.dart
  admin-frontend/open_admin_app/lib/common/stream_valley.dart
  admin-frontend/open_admin_app/lib/widgets/user/signin/signin_widget.dart
Labels: bug

#952 Details of NATS channels used by FeatureHub
  docs/modules/ROOT/pages/configuration.adoc
Labels: enhancement

#960 [feature/auditing] Always enabled Auditing
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
Labels: enhancement

#961 [internal/fix] Remove permission for create feature
  backend/mr-db-api/src/main/java/io/featurehub/db/api/PersonFeaturePermission.java
Labels: bug, enhancement

#962 fix feature create permission to show "create feature" button. Plus Lock/Unlock allow only when permission set
  admin-frontend/open_admin_app/lib/routes/features_overview_route.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/lock_unlock_switch.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/create_update_feature_dialog_widget.dart
Labels: bug, enhancement

#964 fix metadata editing permission
  admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/set_feature_metadata.dart
Labels: bug

#967 Docs - add SDKs section to hosted
  docs/modules/ROOT/nav.adoc
Labels: docs

#963 Feature/capture update details
  backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/FeatureApi.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingLockUnitSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingRetiredUnitSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingStrategiesUnitSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingValueUnitSpec.groovy
Labels: enhancement

#971 [internal/feature-perm-fixup] Feature perms not remembering past 1st
  admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
Labels: bug, enhancement

#966 New API docs bucket
  infra/api-bucket/index.ts
Labels: docs

#974 Fixed Helm Repo Link in Documentation
  docs/modules/ROOT/pages/installation.adoc
Labels: bug

#980 [internal/minor-dep-fixes] More minor dependency fixes
  backend/composite-common/pom.xml
  backend/composite-jersey/pom.xml
  backend/mr-db-ebean/src/main/resources/ebean.mf
Labels: bug, dependencies

#951 Swift SDK + updates to details of SDKs
  docs/modules/ROOT/pages/capabilities-table.adoc
Labels: enhancement

#979 Feature/messaging cloud event
  adks/e2e-sdk/app/steps/webhook_steps.ts
  adks/e2e-sdk/app/support/make_me_a_webserver.ts
  backend/messaging-api/messaging-api.yaml
  backend/messaging-api/pom.xml
  backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/FeatureApi.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Base3Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingBaseUnitSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureUpdatesPublishingSpec.groovy
  backend/mr-eventing-common/pom.xml
  backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/FeatureMessagingCloudEventPublisher.kt
  backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/converter/FeatureMessagingConverter.kt
  backend/mr-eventing/pom.xml
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/converter/FeatureMessagingConverterImpl.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/service/FeatureMessagingCloudEventPublisherImpl.kt
  backend/mr-eventing/src/test/groovy/io/featurehub/mr/events/common/BaseSpecificationWithFeatureSetup.groovy
  backend/mr-eventing/src/test/groovy/io/featurehub/mr/events/converter/FeatureMessagingConverterImplSpec.groovy
  backend/mr-eventing/src/test/groovy/io/featurehub/mr/events/service/FeatureMessagingCloudEventPublisherImplSpec.groovy
  pom.xml
Labels: enhancement

#984 [feature/dacha1-ui-refresh] Allow refresh of Dacha1 cache from UI
  admin-frontend/open_admin_app/lib/api/identity_providers.dart
  admin-frontend/open_admin_app/lib/routes/apps_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_portfolios_route.dart
  admin-frontend/open_admin_app/lib/widgets/apps/apps_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/portfolio/portfolio_bloc.dart
  backend/composite-ebean/pom.xml
  backend/mr-api/mr-api.yaml
  backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/CacheRefresherApi.kt
  backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CacheBroadcast.kt
  backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CacheSource.kt
  backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CloudEventCacheBroadcaster.kt
  backend/mr-eventing-nats/src/main/kotlin/io/featurehub/db/publish/nats/NatsDachaBroadcaster.kt
  backend/mr-eventing-nats/src/main/kotlin/io/featurehub/db/publish/nats/NatsDachaCacheFiller.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/DummyPublisher.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt
  backend/mr/src/main/java/io/featurehub/mr/resources/SetupResource.java
  backend/mr/src/main/kotlin/io/featurehub/mr/ManagementRepositoryFeature.kt
  backend/mr/src/main/kotlin/io/featurehub/mr/resources/CacheResource.kt
  backend/mr/src/main/kotlin/io/featurehub/mr/utils/ConfigurationUtils.kt
  backend/mr/src/main/resources/deploy-defaults/common.properties
  backend/party-server-ish/src/main/kotlin/io.featurehub.party/Application.kt
  backend/party-server/src/main/kotlin/io.featurehub.party/Application.kt
  infra/api-bucket/files/mrapi/1.1.11.yaml
Labels: enhancement
