Repository featurehub-io/featurehub, pull requests merged in 2023-01, with the labels that each got.

#908 Minor internal UI adjustments
  admin-frontend/open_admin_app/lib/routes/apps_route.dart
  admin-frontend/open_admin_app/lib/widgets/features/cell-view/value_cell.dart
Labels: improvement

#911 Minor dashboard repair
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/features_data_table.dart
  admin-frontend/open_admin_app/pubspec.yaml
Labels: improvement

#912 UI improvement - handle bloc dispose
  admin-frontend/open_admin_app/lib/api/client_api.dart
  admin-frontend/open_admin_app/lib/routes/features_overview_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_app_route.dart
  admin-frontend/open_admin_app/lib/theme/theme_data.dart
  admin-frontend/open_admin_app/lib/widgets/apps/apps_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_underline_button.dart
  admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_bloc.dart
Labels: improvement

#914 UI dashboard - add tooltip to the feature name
  admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/lock_unlock_switch.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/feature_cell_holder.dart
Labels: enhancement, improvement

#915 [internal/lib-fix-cloudevents] Fake registry not setting source
  admin-frontend/cli/pubspec.yaml
  backend/enricher-processor/src/main/kotlin/io/featurehub/enricher/EnricherConfig.kt
  backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventReceiverRegistry.kt
  backend/mr/src/main/java/io/featurehub/mr/resources/SetupResource.java
  backend/webhook-feature-update/src/main/kotlin/io/features/webhooks/features/WebhookFeature.kt
Labels: bug

#918 change version and docs ready for 1.6.0
  current-rc.txt
  docs/antora.yml
Labels: docs

#919 [internal/webhook-docs] Documentation for webhooks
  backend/enricher-api/enricher-api.yaml
  backend/enricher-api/internal-enricher-api.yaml
  backend/enricher-api/pom.xml
  backend/webhook-feature-update/sinatra-example/Gemfile.lock
  backend/webhook-feature-update/src/main/kotlin/io/features/webhooks/features/WebhookFeature.kt
  docs/modules/ROOT/images/webhook_config.png
  docs/modules/ROOT/images/webhook_details.png
  docs/modules/ROOT/images/webhook_view.png
  docs/modules/ROOT/images/webhooks_menu.png
  docs/modules/ROOT/images/webhooks_overview_architecture.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/configuration.adoc
  docs/modules/ROOT/pages/webhooks-configuration.adoc
  docs/modules/ROOT/pages/webhooks.adoc
  infra/api-bucket/files/webhooks/1.1.1.yaml
  infra/api-bucket/files/webhooks/releases.json
Labels: docs

#920 additional dashboard UI updates
  admin-frontend/open_admin_app/lib/widgets/features/cell-view/flag_colored_on_off_label.dart
  admin-frontend/open_admin_app/lib/widgets/features/cell-view/value_cell.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/feature_cell_holder.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/features_data_table.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature_dashboard_constants.dart
Labels: enhancement

#921 Docs and readme update
  docs/images/languages.png
  docs/modules/ROOT/pages/sdks.adoc
  readme.adoc
Labels: docs

#925 fixes for 1.6.0-RC release
  adks/e2e-sdk/app/steps/flag_steps.ts
  adks/e2e-sdk/app/steps/setup.ts
  adks/e2e-sdk/app/support/hooks.ts
  adks/e2e-sdk/app/support/make_me_a_webserver.ts
  adks/e2e-sdk/features/webhooks.feature
  adks/e2e-sdk/package-lock.json
  adks/e2e-sdk/package.json
  backend/dacha2/src/test/resources/log4j2-test.xml
  backend/edge-full/src/test/resources/log4j2-test.xml
  backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventPublisherRegistry.kt
  backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventReceiverRegistry.kt
  backend/mr-eventing-nats/src/main/kotlin/io/featurehub/db/publish/nats/NatsDachaEventingFeature.kt
  backend/mr-eventing-nats/src/main/kotlin/io/featurehub/mr/events/nats/NatsCloudEventsBroadcaster.kt
  backend/mr/src/test/resources/log4j2-test.xml
  backend/party-server/src/test/resources/application.properties
Labels: bug
