Repository featurehub-io/featurehub, pull requests merged in 2023-09, with the labels that each got.

#1058 [bugfix/missing-webhooks] Concurrent hashmap webhook issue
  adks/e2e-sdk/Dockerfile
  adks/e2e-sdk/app/steps/setup.ts
  adks/e2e-sdk/package.json
  adks/e2e-sdk/run-e2e.sh
  admin-frontend/open_admin_app/lib/api/client_api.dart
  backend/common-web/src/main/kotlin/io/featurehub/health/CommonFeatureHubFeatures.kt
  backend/common-web/src/main/kotlin/io/featurehub/jersey/ManagedAsyncThreadPoolExecutorProvider.kt
  backend/common-web/src/main/kotlin/io/featurehub/lifecycle/TelemetryFeature.kt
  backend/common-web/src/main/kotlin/io/featurehub/utils/ExecutorUtil.kt
  backend/dacha/src/main/java/io/featurehub/dacha/EnvironmentFeatures.java
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheImpl.kt
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CloudEventListenerImpl.kt
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/FeatureValuesFactory.kt
  backend/dacha2/src/test/groovy/io/featurehub/dacha2/Dacha2CacheImplSpec.groovy
  backend/dacha2/src/test/groovy/io/featurehub/dacha2/EnvironmentFeaturesSpec.groovy
  backend/dacha2/src/test/groovy/io/featurehub/dacha2/FeatureHolderThread.groovy
  backend/edge-common/src/main/java/io/featurehub/edge/strategies/ApplyFeature.java
  backend/edge-common/src/main/java/io/featurehub/edge/strategies/ClientContext.java
  backend/edge-common/src/test/groovy/io/featurehub/edge/strategies/ApplyFeatureSpec.groovy
  backend/edge-full/src/main/java/io/featurehub/edge/Application.java
  backend/edge-full/src/main/java/io/featurehub/edge/EdgeFeature.java
  backend/edge-full/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java
  backend/edge-full/src/main/kotlin/io/featurehub/edge/client/EventOutputHolder.kt
  backend/edge-full/src/main/kotlin/io/featurehub/edge/client/TimedBucketClientFactory.kt
  backend/edge-full/src/test/groovy/io/featurehub/edge/client/TimedBucketClientConnectionSpec.groovy
  backend/enricher-processor/src/main/kotlin/io/featurehub/enricher/FeatureEnricher.kt
  backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventPublisherRegistry.kt
  backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventReceiverRegistry.kt
  backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventsTelemetryReaderImpl.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr/src/main/java/io/featurehub/mr/auth/AuthApplicationEventListener.java
  backend/mr/src/main/kotlin/io/featurehub/mr/ManagementRepositoryFeature.kt
  backend/mr/src/main/kotlin/io/featurehub/mr/auth/BaggageSourceAuth.kt
  backend/party-server/src/test/resources/log4j2-test.xml
  backend/sdk-strategy-matchers/src/test/groovy/io/featurehub/strategies/matchers/StringArrayMatcherSpec.groovy
  backend/webhook-feature-update/src/main/kotlin/io/features/webhooks/features/WebhookFeature.kt
Labels: bug

#1054 [feature/feature-group-publishing] Backend support for Feature Groups
  adks/e2e-sdk/app/steps/environment.ts
  adks/e2e-sdk/app/steps/feature-groups.ts
  adks/e2e-sdk/app/steps/flag_steps.ts
  adks/e2e-sdk/app/steps/setup.ts
  adks/e2e-sdk/app/steps/strategies.ts
  adks/e2e-sdk/app/support/hooks.ts
  adks/e2e-sdk/app/support/world.ts
  adks/e2e-sdk/features/feature-groups.feature
  adks/e2e-sdk/package-lock.json
  adks/e2e-sdk/package.json
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheImpl.kt
  backend/mr-api/feature-group.yaml
  backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/FeatureGroupApi.kt
  backend/mr-db-models/src/main/java/io/featurehub/db/model/DbFeatureGroup.java
  backend/mr-db-sql/src/main/java/io/featurehub/db/utils/ApiToSqlApiBinder.java
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ApplicationSqlApi.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ArchiveStrategy.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/DbArchiveStrategy.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureGroupSqlApi.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ApplicationSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AuthenticationSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Base3Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureGroupSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureStandaloneSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureUpdatesPublishingSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/GroupSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ServiceAccount2Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/UserStateSpec.groovy
  backend/mr-db-sql/src/test/resources/log4j2-test.xml
  backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/CacheSourceFeatureGroupApi.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt
  backend/mr/src/main/kotlin/io/featurehub/mr/resources/FeatureGroupResource.kt
  infra/api-bucket/files/mrapi/1.1.12.yaml
Labels: enhancement

#1061 Internal/fg feature delete
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ArchiveStrategy.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/DbArchiveStrategy.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureGroupSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureGroupSpec.groovy
Labels: enhancement

#1062 [bugfix/various] bug fixes
  backend/common-web/src/main/java/io/featurehub/jersey/config/LocalExceptionMapper.java
  backend/common-web/src/main/kotlin/io/featurehub/lifecycle/TelemetryFeature.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureGroupSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureGroupSpec.groovy
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt
  backend/party-server-ish/src/test/resources/application.properties
Labels: bug

#1064 Feature/Add API documentation to the docs.featurehub.io
  docs/modules/ROOT/attachments/api.yaml
  docs/modules/ROOT/attachments/sdk-api.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/admin-development-kit.adoc
  docs/modules/ROOT/pages/api-definition.adoc
  docs/modules/ROOT/pages/sdk-api-definition.adoc
  docs/modules/ROOT/pages/sdks.adoc
  docs/supplemental_ui/css/style.css
  docs/supplemental_ui/partials/head-styles.hbs
Labels: enhancement, docs

#1065 Update ADK API docs yaml file
  docs/modules/ROOT/attachments/api.yaml
Labels: docs

#1069 Readme updates
  docs/images/eroad-logo.png
  readme.adoc
Labels: docs
