Repository featurehub-io/featurehub, pull requests merged in 2023-03, with the labels that each got.

#930 add docs nav extension
  docs/antora-playbook.yml
  docs/modules/ROOT/nav.adoc
Labels: docs

#933 add ability to use google analytics on the Admin UI app (optional feature)
  admin-frontend/open_admin_app/lib/api/client_api.dart
  admin-frontend/open_admin_app/lib/common/ga_id.dart
  admin-frontend/open_admin_app/lib/config/route_handlers.dart
  admin-frontend/open_admin_app/lib/routes/admin_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/routes/api_keys_route.dart
  admin-frontend/open_admin_app/lib/routes/apps_route.dart
  admin-frontend/open_admin_app/lib/routes/features_overview_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_app_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_group_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_portfolios_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_service_accounts_route.dart
  admin-frontend/open_admin_app/lib/routes/manage_users_route.dart
  admin-frontend/open_admin_app/lib/routes/register_url_route.dart
  admin-frontend/open_admin_app/lib/routes/setup_route.dart
  admin-frontend/open_admin_app/lib/routes/signin_route.dart
  admin-frontend/open_admin_app/lib/widgets/admin_sdk_service_account/admin_sa_reset_key_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/app_delete_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/app_update_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/apps_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/apps/manage_service_accounts_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/cell-view/strategy_tooltip.dart
  admin-frontend/open_admin_app/lib/widgets/features/cell-view/value_cell.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/feature_value_updated_by.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/json/edit_json_value_container.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/custom_strategy_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/edit_value_strategy_link_button.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/split_rollout_button.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_editing_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/delete_feature_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/feature_cell_holder.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature/set_feature_metadata.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/features_data_source.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/features_data_table.dart
  admin-frontend/open_admin_app/lib/widgets/group/group_update_widget.dart
  admin-frontend/open_admin_app/lib/widgets/service-accounts/apikey_reset_dialog_widget.dart
  admin-frontend/open_admin_app/lib/widgets/service-accounts/service_accounts_env_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/setup/page2_widget.dart
  admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/user/create/create_user_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/user/update/password_reset_widget.dart
  admin-frontend/open_admin_app/pubspec.yaml
  api-reactor.xml
  backend/mr-api/mr-api.yaml
  backend/mr/src/main/java/io/featurehub/mr/resources/SetupResource.java
  docs/modules/ROOT/pages/configuration.adoc
  infra/api-bucket/files/mrapi/1.1.11.yaml
  pipeline/app-build-pipeline/cloudbuild.yaml
Labels: enhancement

#937 Minor fixes for responsive UI
  admin-frontend/open_admin_app/lib/routes/features_overview_route.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/feature-data-table/features_data_table.dart
  readme.adoc
Labels: bug

#942 Ability to add multi comma separated values in the strategies field
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/add_attribute_strategy_widget.dart
Labels: enhancement

#946 Allow for the disabling of prometheus metrics
  backend/composite-jersey/pom.xml
  docs/modules/ROOT/pages/metrics.adoc
Labels: enhancement

#943 [feature/reordering-strategies] Support reordering strategies
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/custom_strategy_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card_widget.dart
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingStrategiesUnitSpec.groovy
Labels: enhancement

#948 Allow for landing overlays on App page
  admin-frontend/open_admin_app/lib/api/client_api.dart
  admin-frontend/open_admin_app/lib/widgets/apps/apps_bloc.dart
Labels: enhancement
