Repository featurehub-io/featurehub, pull requests merged in 2024-07, with the labels that each got.

#1159 slack: fix issue around lower case forced filter
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/SystemConfigSqlApi.kt
Labels: bug, enhancement

#1161 Minor UI-slack config updates
  admin-frontend/open_admin_app/lib/widgets/systemconfig/slack/slack_system_config_widget.dart
  backend/messaging-delivery/src/main/kotlin/io/featurehub/messaging/slack/SlackInternalDeliveryListener.kt
Labels: enhancement

#1162 update slack integration docos
  docs/modules/ROOT/pages/slack-integration.adoc
Labels: docs

#1163 various minor slack updates + docs
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/slack_panel_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/track_events_panel_widget.dart
  admin-frontend/open_admin_app/lib/widgets/setup/page3_widget.dart
  admin-frontend/open_admin_app/lib/widgets/systemconfig/site/site_system_config_widget.dart
  admin-frontend/open_admin_app/lib/widgets/systemconfig/slack/slack_system_config_widget.dart
  backend/messaging-delivery/src/main/kotlin/io/featurehub/messaging/slack/SlackInternalDeliveryListener.kt
  docs/modules/ROOT/images/fh-website-url-config.png
  docs/modules/ROOT/images/slack-install-manifest.png
  docs/modules/ROOT/pages/slack-integration.adoc
  docs/modules/ROOT/pages/system-configuration.adoc
Labels: enhancement, docs

#1165 [fix] set default error page for grizzly web server
  backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt
Labels: bug

#1166 [fix] set slack enabled by default
  backend/mr-db-sql/src/main/kotlin/io/featurehub/systemcfg/SlackClient.kt
  current-rc.txt
Labels: bug

#1164 add system config docs to nav
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/track_events_panel_widget.dart
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: docs

#1167 [fix] initial bool on new environment not publishing
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ApplicationSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Base3Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureUpdatesPublishingSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/GroupSpec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ServiceAccount2Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/UserStateSpec.groovy
Labels: bug

#1168 [bugfix] Service Account Permissions being wiped
  admin-frontend/build-frontend.sh
  admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
  backend/mr-api/mr-api.yaml
  backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/ServiceAccountApi.kt
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ServiceAccountSqlApi.kt
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Base2Spec.groovy
  backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ServiceAccount2Spec.groovy
  backend/mr/src/main/kotlin/io/featurehub/mr/resources/ServiceAccountResource.kt
  infra/api-bucket/files/mrapi/1.2.2.yaml
  infra/api-bucket/files/mrapi/releases.json
Labels: bug

#1170 Fix: convert checkbox to stateful widget to fix permissions for service accounts failing occasionally
  admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
Labels: bug
