Repository featurehub-io/featurehub, pull requests merged in 2024-02, with the labels that each got.

#1118 Feature/sdk extensions
  adks/e2e-sdk/Dockerfile
  adks/e2e-sdk/app/steps/feature-properties.ts
  adks/e2e-sdk/app/steps/setup.ts
  adks/e2e-sdk/app/support/world.ts
  adks/e2e-sdk/features/flags.feature
  adks/e2e-sdk/make-image.sh
  admin-frontend/open_admin_app/lib/api/identity_providers.dart
  admin-frontend/open_admin_app/lib/utils/utils.dart
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
  backend/composite-common/pom.xml
  backend/dacha-api/dacha-api.yaml
  backend/dacha-api/dacha-component.yaml
  backend/dacha/src/main/java/io/featurehub/dacha/EnvironmentFeatures.java
  backend/dacha/src/main/kotlin/io/featurehub/dacha/resource/DachaApiKeyResource.kt
  backend/dacha/src/test/groovy/io/featurehub/dacha/resource/DachaApiKeyResourceSpec.groovy
  backend/dacha2/pom.xml
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheImpl.kt
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CloudEventListenerImpl.kt
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/FeatureValuesFactory.kt
  backend/dacha2/src/main/kotlin/io/featurehub/dacha2/resource/DachaApiKeyResource.kt
  backend/dacha2/src/test/groovy/io/featurehub/dacha2/Dacha2CacheImplSpec.groovy
  backend/dacha2/src/test/groovy/io/featurehub/dacha2/EnvironmentFeaturesSpec.groovy
  backend/dacha2/src/test/groovy/io/featurehub/dacha2/resource/DachaApiKeyResourceSpec.groovy
  backend/edge-api/sse-api.yaml
  backend/edge-common/src/main/java/io/featurehub/edge/FeatureTransformer.java
  backend/edge-common/src/main/java/io/featurehub/edge/FeatureTransformerUtils.java
  backend/edge-common/src/main/kotlin/io/featurehub/edge/features/FeatureRequestCollection.kt
  backend/edge-common/src/main/kotlin/io/featurehub/edge/features/FeatureRequestResponse.kt
  backend/edge-full/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java
  backend/edge-full/src/test/groovy/io/featurehub/edge/features/FeatureRequestCollectionSpec.groovy
  backend/edge-rest/src/main/kotlin/io/featurehub/edge/EdgeGetFeature.kt
  backend/edge-rest/src/main/kotlin/io/featurehub/edge/db/sql/DbDachaCacheSqlApi.kt
  backend/edge-rest/src/main/kotlin/io/featurehub/edge/db/sql/DbDachaSqlApi.kt
  backend/make-apis.sh
  backend/mr-api/end2end-common.yaml
  backend/mr-db-models/src/main/java/io/featurehub/db/model/DbVersionedBase.java
  backend/mr-db-services/pom.xml
  backend/mr-db-services/src/main/kotlin/io/featurehub/db/publish/FeatureModelWalker.kt
  backend/mr-db-services/src/main/kotlin/io/featurehub/db/services/Conversions.kt
  backend/mr-db-services/src/test/groovy/io/featurehub/db/publish/FeatureModelWalkerSpec.groovy
  backend/mr-db-services/src/test/resources/application-test.yaml
  backend/mr-db-services/src/test/resources/test-ebean.properties
  backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ApplicationSqlApi.kt
  backend/mr-eventing/pom.xml
  backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt
  backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt
  backend/mr-eventing/src/test/resources/application-test.yaml
  backend/mr-eventing/src/test/resources/test-ebean.properties
  backend/mr/src/test/resources/application.properties
  backend/party-server-ish/src/test/resources/application.properties
  backend/party-server-ish/src/test/resources/log4j2-test.xml
  backend/party-server/src/test/resources/application.properties
  backend/pom-apis.xml
  docs/modules/ROOT/pages/configuration.adoc
  infra/api-bucket/files/edge/1.1.8.yaml
  infra/api-bucket/files/edge/releases.json
  infra/api-bucket/files/mrapi/1.2.1.yaml
  infra/api-bucket/files/webhooks/1.2.1.yaml
Labels: enhancement

#1120 [internal] minor bugfixes for UI related issues
  admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
Labels: bug

#1122 Minor fix for the group strategy firld hint
  admin-frontend/open_admin_app/lib/widgets/common/fh_flat_button_accent.dart
  admin-frontend/open_admin_app/lib/widgets/feature-groups/feature_group_settings_side_sheet.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_string_value_container.dart
Labels: bug

#1119 Add button for Slack integration + docs
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/slack_panel_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/webhook_environment_table_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/webhook_environment_widget.dart
  admin-frontend/open_admin_app/lib/widgets/common/fh_external_link_outlined_widget.dart
  docs/modules/ROOT/images/1-slack-install-to-workspace.png
  docs/modules/ROOT/images/2-slack-allow-access.png
  docs/modules/ROOT/images/3-slack-copy-oauth-token.png
  docs/modules/ROOT/images/slack-bot-token.png
  docs/modules/ROOT/images/slack-enabled.png
  docs/modules/ROOT/images/slack-fh-integration-page.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/slack-integration.adoc
Labels: docs

#1123 [feature] Support for Zipkin & Jaeger exporters
  backend/common-web/pom.xml
  backend/common-web/src/main/kotlin/io/featurehub/lifecycle/TelemetryFeature.kt
  backend/mr-messaging-channel/src/main/kotlin/io/featurehub/messaging/MessagingPublishingFeature.kt
Labels: enhancement

#1124 Fix docs links
  docs/modules/ROOT/pages/admin-development-kit.adoc
  docs/modules/ROOT/pages/metrics.adoc
  docs/modules/ROOT/pages/sdks.adoc
Labels: bug, docs

#1127 Fix webhook headers editing with single tap
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/webhook_configuration_widget.dart
  admin-frontend/open_admin_app/lib/widgets/apps/webhook/webhook_environment_page_tablesource.dart
Labels: bug

#1126 Update docs index page
  docs/modules/ROOT/pages/capabilities-explained.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/installation.adoc
  docs/modules/ROOT/pages/resilience.adoc
  docs/modules/ROOT/pages/sdks.adoc
Labels: docs

#1128 Update webhooks docs
  docs/modules/ROOT/images/webhook-config.png
  docs/modules/ROOT/images/webhook-log.png
  docs/modules/ROOT/images/webhook_config.png
  docs/modules/ROOT/images/webhook_details.png
  docs/modules/ROOT/images/webhook_history.png
  docs/modules/ROOT/images/webhook_view.png
  docs/modules/ROOT/images/webhooks_menu.png
  docs/modules/ROOT/pages/webhooks.adoc
Labels: docs
