Repository featurehub-io/featurehub, pull requests merged in 2025-03, with the labels that each got.

#1203 App strategy - minor fix error in the create route
  admin-frontend/open_admin_app/lib/config/route_handlers.dart
Labels: bug, enhancement

#1204 App strategy - minor fix strategy roles
  admin-frontend/open_admin_app/lib/common/person_state.dart
Labels: bug, enhancement

#1205 App strategy - minor fix application strategy roles - only allow edit if role is present
  admin-frontend/open_admin_app/lib/widgets/application-strategies/application_strategy_list.dart
Labels: bug, enhancement

#1206 App strategy: fix strategy roles - add appId stream
  admin-frontend/open_admin_app/lib/widgets/application-strategies/application_strategy_bloc.dart
  admin-frontend/open_admin_app/lib/widgets/application-strategies/application_strategy_list.dart
Labels: bug, enhancement

#1207 fix: address non-superuser perms for applicationstrategies
  backend/mr/src/main/kotlin/io/featurehub/mr/resources/ApplicationRolloutStrategyResource.kt
  backend/mr/src/main/kotlin/io/featurehub/mr/utils/ApplicationUtils.kt
Labels: bug

#1208 App strategy - minor text/copy update
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
Labels: enhancement

#1209 App strategy: minor text/copy updates, icon update
  admin-frontend/open_admin_app/lib/widgets/common/fh_drawer.dart
  admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
  docs/modules/ROOT/images/app-strategy-create.png
  docs/modules/ROOT/pages/application-strategies.adoc
Labels: enhancement
